sudo: required

services:
    - docker

language: python
python:
    - "3.6"

jobs:
    include:
        - stage: install
          script: pip install --editable .[ci,dev,doc,gui_react]

        - stage: style
          script: python check.py

        - stage: coverage
          script: coveralls || true

        - stage: deploy
          script: python release.py

stages:
    - install
    - style
    - coverage
    - name: deploy
      if: (branch = master) AND (NOT (type IN (push, pull_request)))
