sudo: required

services:
    - docker

language: python
python:
    - "3.6"

jobs:
    include:
        - stage: style
          script:
              - pip install --editable .[ci,dev,doc,gui_react]
              - python check.py
              - coveralls || true

        - stage: deploy
          script: python release.py

stages:
    - style
    - name: deploy
      if: (branch = master) AND (NOT (type IN (push, pull_request)))
